// <auto-generated />
using Items.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Items.Migrations
{
    [DbContext(typeof(ItemsDbContext))]
    partial class ItemsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Items.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Sport"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Elegant"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Casual"
                        });
                });

            modelBuilder.Entity("Items.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Nike",
                            CategoryId = 1,
                            Color = "Black",
                            Description = "Nike sport shoes for man",
                            ImageUrl = "https://img01.ztat.net/article/spp-media-p1/ccd66a56f6c439c7a4a87f9d365ff8f8/45a85d86e84641a8aeb332255c4353aa.jpg",
                            Price = 239.99m,
                            Title = "Blizzard"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Bytom",
                            CategoryId = 2,
                            Color = "White",
                            Description = "Adidas sport shoes for man",
                            ImageUrl = "https://www.bytom.com.pl/files/sc_staging_images/product/normal_img_43791.jpg",
                            Price = 499.99m,
                            Title = "Melvin"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Kso Evo",
                            CategoryId = 2,
                            Color = "Blue",
                            Description = "Walking shoes",
                            ImageUrl = "https://img01.ztat.net/article/spp-media-p1/7915e22f5a323fed81631f9f87aee165/3493cf55c5b1422cbd8614c7c4184af6.jpg?imwidth=1800&filter=packshot",
                            Price = 439.99m,
                            Title = "Kso walking"
                        });
                });

            modelBuilder.Entity("Items.Entities.Item", b =>
                {
                    b.HasOne("Items.Entities.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Items.Entities.Category", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
